name: Deploy to GitHub pages
on:
  push:
    # this is the branch where you develop your site
    # as discussed in the publishing sources section
    # this can change if you are using an user/organization repo
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: start python server
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Init new repo in dist folder and commit generated files
      run: |
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m 'deploy'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
        directory: /
 

