name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: copy
        run: |
          cp script
          python simple-cors-http-server.py
      - name: Deploy
        run: |
          python simple-cors-http-server.py
   
     
 

